version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "${API_PORT:-4000}:4000"
    environment:
      API_DB: 'postgres://postgres:mysecretpassword@db:5432/postgres'
    entrypoint: >
      bash -c "sh wait_components.sh
      && env PYTHONPATH=src python src/api/migrate.py db upgrade
      && sh run_api.sh"
  db:
    image: postgres:11.4
    ports:
      - "${HEALTHDB:-3309}:3306"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
